// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteNumbersByNumberData, DeleteNumbersByNumberErrors, DeleteNumbersByNumberResponses, GetNumbersByNumberData, GetNumbersByNumberErrors, GetNumbersByNumberResponses, GetNumbersData, GetNumbersErrors, GetNumbersResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PostNumbersCheckData, PostNumbersCheckResponses, PostNumbersData, PostNumbersErrors, PostNumbersResponses, PutNumbersByNumberData, PutNumbersByNumberErrors, PutNumbersByNumberResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>) => (options.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getNumbers = <ThrowOnError extends boolean = false>(options: Options<GetNumbersData, ThrowOnError>) => (options.client ?? client).get<GetNumbersResponses, GetNumbersErrors, ThrowOnError>({ url: '/numbers', ...options });

export const postNumbers = <ThrowOnError extends boolean = false>(options: Options<PostNumbersData, ThrowOnError>) => (options.client ?? client).post<PostNumbersResponses, PostNumbersErrors, ThrowOnError>({
    url: '/numbers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteNumbersByNumber = <ThrowOnError extends boolean = false>(options: Options<DeleteNumbersByNumberData, ThrowOnError>) => (options.client ?? client).delete<DeleteNumbersByNumberResponses, DeleteNumbersByNumberErrors, ThrowOnError>({ url: '/numbers/{number}', ...options });

export const getNumbersByNumber = <ThrowOnError extends boolean = false>(options: Options<GetNumbersByNumberData, ThrowOnError>) => (options.client ?? client).get<GetNumbersByNumberResponses, GetNumbersByNumberErrors, ThrowOnError>({ url: '/numbers/{number}', ...options });

export const putNumbersByNumber = <ThrowOnError extends boolean = false>(options: Options<PutNumbersByNumberData, ThrowOnError>) => (options.client ?? client).put<PutNumbersByNumberResponses, PutNumbersByNumberErrors, ThrowOnError>({
    url: '/numbers/{number}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postNumbersCheck = <ThrowOnError extends boolean = false>(options: Options<PostNumbersCheckData, ThrowOnError>) => (options.client ?? client).post<PostNumbersCheckResponses, unknown, ThrowOnError>({
    url: '/numbers/check',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
