// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

export type Error = {
    error: string;
    code: 100 | 101 | 102 | 103 | 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207 | 208 | 300 | 301 | 302 | 303 | 304 | 307 | 308 | 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 420 | 421 | 422 | 423 | 424 | 425 | 426 | 428 | 429 | 431 | 451 | 500 | 501 | 502 | 503 | 504 | 505 | 506 | 507 | 508 | 510 | 511;
};

export type PostAuthLoginData = {
    body: {
        login: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Response for status 400
     */
    400: Error;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Response for status 200
     */
    200: {
        token: string;
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetNumbersData = {
    body?: never;
    headers: {
        authorization: string;
    };
    path?: never;
    query?: never;
    url: '/numbers';
};

export type GetNumbersErrors = {
    /**
     * Response for status 401
     */
    401: Error;
};

export type GetNumbersError = GetNumbersErrors[keyof GetNumbersErrors];

export type GetNumbersResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        number: string;
        car: string;
        userId: number;
    }>;
};

export type GetNumbersResponse = GetNumbersResponses[keyof GetNumbersResponses];

export type PostNumbersData = {
    body: {
        number: string;
        car: string;
        userId: number;
    };
    headers: {
        authorization: string;
    };
    path?: never;
    query?: never;
    url: '/numbers';
};

export type PostNumbersErrors = {
    /**
     * Response for status 401
     */
    401: Error;
};

export type PostNumbersError = PostNumbersErrors[keyof PostNumbersErrors];

export type PostNumbersResponses = {
    /**
     * Response for status 200
     */
    200: {
        number: string;
        car: string;
        userId: number;
    };
};

export type PostNumbersResponse = PostNumbersResponses[keyof PostNumbersResponses];

export type DeleteNumbersByNumberData = {
    body?: never;
    headers: {
        authorization: string;
    };
    path: {
        number: string;
    };
    query?: never;
    url: '/numbers/{number}';
};

export type DeleteNumbersByNumberErrors = {
    /**
     * Response for status 401
     */
    401: Error;
    /**
     * Response for status 404
     */
    404: Error;
};

export type DeleteNumbersByNumberError = DeleteNumbersByNumberErrors[keyof DeleteNumbersByNumberErrors];

export type DeleteNumbersByNumberResponses = {
    /**
     * Response for status 200
     */
    200: {
        number: string;
        car: string;
        userId: number;
    };
};

export type DeleteNumbersByNumberResponse = DeleteNumbersByNumberResponses[keyof DeleteNumbersByNumberResponses];

export type GetNumbersByNumberData = {
    body?: never;
    headers: {
        authorization: string;
    };
    path: {
        number: string;
    };
    query?: never;
    url: '/numbers/{number}';
};

export type GetNumbersByNumberErrors = {
    /**
     * Response for status 401
     */
    401: Error;
    /**
     * Response for status 404
     */
    404: Error;
};

export type GetNumbersByNumberError = GetNumbersByNumberErrors[keyof GetNumbersByNumberErrors];

export type GetNumbersByNumberResponses = {
    /**
     * Response for status 200
     */
    200: {
        number: string;
        car: string;
        userId: number;
    };
};

export type GetNumbersByNumberResponse = GetNumbersByNumberResponses[keyof GetNumbersByNumberResponses];

export type PutNumbersByNumberData = {
    body: {
        number?: string;
        car?: string;
        userId?: number;
    };
    headers: {
        authorization: string;
    };
    path: {
        number: string;
    };
    query?: never;
    url: '/numbers/{number}';
};

export type PutNumbersByNumberErrors = {
    /**
     * Response for status 401
     */
    401: Error;
    /**
     * Response for status 404
     */
    404: Error;
};

export type PutNumbersByNumberError = PutNumbersByNumberErrors[keyof PutNumbersByNumberErrors];

export type PutNumbersByNumberResponses = {
    /**
     * Response for status 200
     */
    200: {
        number: string;
        car: string;
        userId: number;
    };
};

export type PutNumbersByNumberResponse = PutNumbersByNumberResponses[keyof PutNumbersByNumberResponses];

export type PostNumbersCheckData = {
    body: {
        file: unknown;
    };
    path?: never;
    query?: never;
    url: '/numbers/check';
};

export type PostNumbersCheckResponses = {
    /**
     * Response for status 200
     */
    200: {
        number: string;
    };
};

export type PostNumbersCheckResponse = PostNumbersCheckResponses[keyof PostNumbersCheckResponses];
