// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

export type Error = {
    error: string;
};

export type PostAuthLoginData = {
    body: {
        login: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Response for status 400
     */
    400: Error;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Response for status 200
     */
    200: {
        token: string;
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetNumbersData = {
    body?: never;
    headers: {
        authorization: string;
    };
    path?: never;
    query?: never;
    url: '/numbers';
};

export type GetNumbersErrors = {
    /**
     * Response for status 401
     */
    401: Error;
};

export type GetNumbersError = GetNumbersErrors[keyof GetNumbersErrors];

export type GetNumbersResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        number: string;
        car: string;
        userId: number;
    }>;
};

export type GetNumbersResponse = GetNumbersResponses[keyof GetNumbersResponses];

export type PostNumbersData = {
    body: {
        number: string;
        car: string;
        userId: number;
    };
    headers: {
        authorization: string;
    };
    path?: never;
    query?: never;
    url: '/numbers';
};

export type PostNumbersErrors = {
    /**
     * Response for status 401
     */
    401: Error;
};

export type PostNumbersError = PostNumbersErrors[keyof PostNumbersErrors];

export type PostNumbersResponses = {
    /**
     * Response for status 200
     */
    200: {
        number: string;
        car: string;
        userId: number;
    };
};

export type PostNumbersResponse = PostNumbersResponses[keyof PostNumbersResponses];

export type DeleteNumbersByNumberData = {
    body?: never;
    headers: {
        authorization: string;
    };
    path: {
        number: string;
    };
    query?: never;
    url: '/numbers/{number}';
};

export type DeleteNumbersByNumberErrors = {
    /**
     * Response for status 401
     */
    401: Error;
    /**
     * Response for status 404
     */
    404: Error;
};

export type DeleteNumbersByNumberError = DeleteNumbersByNumberErrors[keyof DeleteNumbersByNumberErrors];

export type DeleteNumbersByNumberResponses = {
    /**
     * Response for status 200
     */
    200: {
        number: string;
        car: string;
        userId: number;
    };
};

export type DeleteNumbersByNumberResponse = DeleteNumbersByNumberResponses[keyof DeleteNumbersByNumberResponses];

export type GetNumbersByNumberData = {
    body?: never;
    headers: {
        authorization: string;
    };
    path: {
        number: string;
    };
    query?: never;
    url: '/numbers/{number}';
};

export type GetNumbersByNumberErrors = {
    /**
     * Response for status 401
     */
    401: Error;
    /**
     * Response for status 404
     */
    404: Error;
};

export type GetNumbersByNumberError = GetNumbersByNumberErrors[keyof GetNumbersByNumberErrors];

export type GetNumbersByNumberResponses = {
    /**
     * Response for status 200
     */
    200: {
        number: string;
        car: string;
        userId: number;
    };
};

export type GetNumbersByNumberResponse = GetNumbersByNumberResponses[keyof GetNumbersByNumberResponses];

export type PutNumbersByNumberData = {
    body: {
        number?: string;
        car?: string;
        userId?: number;
    };
    headers: {
        authorization: string;
    };
    path: {
        number: string;
    };
    query?: never;
    url: '/numbers/{number}';
};

export type PutNumbersByNumberErrors = {
    /**
     * Response for status 401
     */
    401: Error;
    /**
     * Response for status 404
     */
    404: Error;
};

export type PutNumbersByNumberError = PutNumbersByNumberErrors[keyof PutNumbersByNumberErrors];

export type PutNumbersByNumberResponses = {
    /**
     * Response for status 200
     */
    200: {
        number: string;
        car: string;
        userId: number;
    };
};

export type PutNumbersByNumberResponse = PutNumbersByNumberResponses[keyof PutNumbersByNumberResponses];

export type PostNumbersCheckData = {
    body: {
        file: unknown;
    };
    path?: never;
    query?: never;
    url: '/numbers/check';
};

export type PostNumbersCheckResponses = {
    /**
     * Response for status 200
     */
    200: {
        message: string;
    };
};

export type PostNumbersCheckResponse = PostNumbersCheckResponses[keyof PostNumbersCheckResponses];
